### ISSUE TITLE
More values to PAE jiffy slider

### ISSUE THREAD

**Issue by jtdelmundo** [bl1231/bilbomd-worker#481]
Right now the PAE Jiffy slider gives you the options 1.5, 2, 5, and 10

I have found that there are many cases where 5 gives you too many clusters for charmm but 3 or 4 is okay. I did those by running the pae_ratios script.

It would be good to either have slider options for 3 and 4, or just a manual input.

**Comment by dsclassen** [comment]
I've added increments of `1`
Closing for now
